# Generated by Django 4.2.15 on 2024-08-08 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_id', models.IntegerField(default=0)),
                ('terminal_degree', models.CharField(max_length=255)),
                ('professional_health_program', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_element', models.BooleanField(default=False)),
                ('element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.element')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='myapp.section')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subsection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='myapp.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubgroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubgroup_responses', to='myapp.responder')),
                ('subsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.responsetopic')),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_responses', to='myapp.responder')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='myapp.subsection')),
            ],
        ),
        migrations.AddField(
            model_name='responsetopic',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.topic'),
        ),
        migrations.CreateModel(
            name='ProcessedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('subsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.responsetopic')),
            ],
        ),
        migrations.AddField(
            model_name='element',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='myapp.topic'),
        ),
    ]
