# Generated by Django 4.2.15 on 2024-08-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responder',
            name='program_category',
            field=models.CharField(default='MISC', max_length=10),
        ),
    ]
