# Generated by Django 4.2.15 on 2024-08-08 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_responder_program_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedResponseAnatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('subsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_responses_anatomy', to='myapp.responsetopic')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedResponseClinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rating', models.FloatField()),
                ('subsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_responses_clinician', to='myapp.responsetopic')),
            ],
        ),
        migrations.CreateModel(
            name='ResponderClinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_id', models.IntegerField(default=0)),
                ('terminal_degree', models.CharField(max_length=255)),
                ('professional_health_program', models.CharField(max_length=255)),
                ('program_category', models.CharField(default='MISC', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupResponseAnatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubgroupResponseClinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_responses_clinician', to='myapp.responderclinician')),
                ('subgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_clinician', to='myapp.subsection')),
            ],
        ),
        migrations.CreateModel(
            name='SubSubgroupResponseAnatomy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SubSubgroupResponseClinician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubgroup_responses_clinician', to='myapp.responderclinician')),
                ('subsubgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_clinician', to='myapp.responsetopic')),
            ],
        ),
        migrations.RemoveField(
            model_name='subgroupresponse',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='subgroupresponse',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='subsubgroupresponse',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='subsubgroupresponse',
            name='subsubgroup',
        ),
        migrations.RenameModel(
            old_name='Responder',
            new_name='ResponderAnatomy',
        ),
        migrations.DeleteModel(
            name='ProcessedResponse',
        ),
        migrations.DeleteModel(
            name='SubgroupResponse',
        ),
        migrations.DeleteModel(
            name='SubSubgroupResponse',
        ),
        migrations.AddField(
            model_name='subsubgroupresponseanatomy',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubgroup_responses_anatomy', to='myapp.responderanatomy'),
        ),
        migrations.AddField(
            model_name='subsubgroupresponseanatomy',
            name='subsubgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_anatomy', to='myapp.responsetopic'),
        ),
        migrations.AddField(
            model_name='subgroupresponseanatomy',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgroup_responses_anatomy', to='myapp.responderanatomy'),
        ),
        migrations.AddField(
            model_name='subgroupresponseanatomy',
            name='subgroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses_anatomy', to='myapp.subsection'),
        ),
    ]
