# Generated by Django 4.2.15 on 2024-08-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_responderclinician_primary_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='average_rating',
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='dds_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='do_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='grd_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='md_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='misc_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='overall_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='pa_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='pt_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='ug_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
