# Generated by Django 4.2.15 on 2024-09-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_processedresponseclinician_average_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedresponseclinician',
            old_name='dds_rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='do_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='grd_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='md_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='misc_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='pa_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='pt_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseclinician',
            name='ug_rating',
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='primary_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='professional_health_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseclinician',
            name='subfield',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
