# Generated by Django 4.2.15 on 2024-09-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_dds_rating_processedresponseclinician_average_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedresponseclinician',
            name='rating_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
