# Generated by Django 4.2.15 on 2024-09-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_processedresponseclinician_rating_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processedresponseanatomy',
            old_name='dds_rating',
            new_name='average_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='do_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='grd_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='md_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='misc_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='overall_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='pa_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='pt_rating',
        ),
        migrations.RemoveField(
            model_name='processedresponseanatomy',
            name='ug_rating',
        ),
        migrations.AddField(
            model_name='processedresponseanatomy',
            name='professional_health_program',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='processedresponseanatomy',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
